CoinBroker/grails-app/domain/com/coinbroker/BuyTokenLot.groovy
package com.coinbroker

/**
 * BuyTokenLot
 * Lot of tokens from a buy or transfer into wallet
 */
class BuyTokenLot extends TokenLot {
    static hasMany = [sellLots: SellTokenLot]

    boolean depleted // True if all token in the lot were sold or used

    static belongsTo = [buyAccount: Account]

    static mapping = {
        depleted sqlType: "tinyint(1)"
    }

    public BuyTokenLot() {
        super()
        // Defaults
        action = ACTION_BUY
        depleted = false
    }

    BigDecimal getRemaining() {
        def amountLeft = amount - sellLots.collect { it.amount }.sum()
        if (amountLeft <= 0) { // should have error if amountLeft < 0
            this.depleted = true
            this.save()
        }
        amountLeft
    }

}

CoinBroker/grails-app/controllers/com/coinbroker/BuyTokenLotController.groovy
package com.coinbroker

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class BuyTokenLotController {

    BuyTokenLotService buyTokenLotService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond buyTokenLotService.list(params), model:[buyTokenLotCount: buyTokenLotService.count()]
    }

    def show(Long id) {
        respond buyTokenLotService.get(id)
    }

    def create() {
        respond new BuyTokenLot(params)
    }

    def save(BuyTokenLot buyTokenLot) {
        if (buyTokenLot == null) {
            notFound()
            return
        }

        try {
            buyTokenLotService.save(buyTokenLot)
        } catch (ValidationException e) {
            respond buyTokenLot.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'buyTokenLot.label', default: 'BuyTokenLot'), buyTokenLot.id])
                redirect buyTokenLot
            }
            '*' { respond buyTokenLot, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond buyTokenLotService.get(id)
    }

    def update(BuyTokenLot buyTokenLot) {
        if (buyTokenLot == null) {
            notFound()
            return
        }

        try {
            buyTokenLotService.save(buyTokenLot)
        } catch (ValidationException e) {
            respond buyTokenLot.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'buyTokenLot.label', default: 'BuyTokenLot'), buyTokenLot.id])
                redirect buyTokenLot
            }
            '*'{ respond buyTokenLot, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        buyTokenLotService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'buyTokenLot.label', default: 'BuyTokenLot'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'buyTokenLot.label', default: 'BuyTokenLot'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

CoinBroker/grails-app/views/buyTokenLot/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'buyTokenLot.label', default: 'BuyTokenLot')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-buyTokenLot" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-buyTokenLot" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.buyTokenLot}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.buyTokenLot}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.buyTokenLot}" method="POST">
                <fieldset class="form">
                    <f:all bean="buyTokenLot"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

CoinBroker/grails-app/views/buyTokenLot/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'buyTokenLot.label', default: 'BuyTokenLot')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-buyTokenLot" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-buyTokenLot" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.buyTokenLot}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.buyTokenLot}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.buyTokenLot}" method="PUT">
                <g:hiddenField name="version" value="${this.buyTokenLot?.version}" />
                <fieldset class="form">
                    <f:all bean="buyTokenLot"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

CoinBroker/grails-app/views/buyTokenLot/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'buyTokenLot.label', default: 'BuyTokenLot')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-buyTokenLot" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-buyTokenLot" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${buyTokenLotList}" />

            <div class="pagination">
                <g:paginate total="${buyTokenLotCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

CoinBroker/grails-app/views/buyTokenLot/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'buyTokenLot.label', default: 'BuyTokenLot')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-buyTokenLot" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-buyTokenLot" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="buyTokenLot" />
            <g:form resource="${this.buyTokenLot}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.buyTokenLot}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>