CoinBroker/grails-app/domain/com/coinbroker/WalletAccount.groovy
package com.coinbroker

import java.security.SecureRandom

/**
 * WalletAccount
 * Internal Wallet account.
 */
class WalletAccount extends Account implements WalletAccountTraits {
    static constraints = {
        currencyType display: false
        monitoring display: false
        mode display: false
        saveCredentials display: false
    }

    public WalletAccount() {
        super()
        // Defaults
        currencyType = Constants.CURRENCY_WELLCOIN
        monitoring = MONITOR_VIRTUAL
        mode = MODE_BOTH
        saveCredentials = true

//        if (credentials == null) {
//            def realWallet = createWallet()
//            credentials = realWallet.credentials
//        }
    }

    def createWallet() {
        // TODO: neet to call wallet API here
        def credentials = new WalletCredentials(
                publicKey: randomKey(),
                privateKey: randomKey(),
        )
        [ credentials: credentials ]
    }

    static transients = ['random']
    SecureRandom random = new SecureRandom();
    def randomKey() {
        def bytes = new byte[20]
        random.nextBytes(bytes)
    }
}

CoinBroker/grails-app/controllers/com/coinbroker/WalletAccountController.groovy
package com.coinbroker

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class WalletAccountController {

    WalletAccountService walletAccountService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond walletAccountService.list(params), model:[walletAccountCount: walletAccountService.count()]
    }

    def show(Long id) {
        respond walletAccountService.get(id)
    }

    def create() {
        respond new WalletAccount(params)
    }

    def save(WalletAccount walletAccount) {
        if (walletAccount == null) {
            notFound()
            return
        }

        try {
            walletAccountService.save(walletAccount)
        } catch (ValidationException e) {
            respond walletAccount.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'walletAccount.label', default: 'WalletAccount'), walletAccount.id])
                redirect walletAccount
            }
            '*' { respond walletAccount, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond walletAccountService.get(id)
    }

    def update(WalletAccount walletAccount) {
        if (walletAccount == null) {
            notFound()
            return
        }

        try {
            walletAccountService.save(walletAccount)
        } catch (ValidationException e) {
            respond walletAccount.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'walletAccount.label', default: 'WalletAccount'), walletAccount.id])
                redirect walletAccount
            }
            '*'{ respond walletAccount, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        walletAccountService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'walletAccount.label', default: 'WalletAccount'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'walletAccount.label', default: 'WalletAccount'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

CoinBroker/grails-app/views/walletAccount/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'walletAccount.label', default: 'WalletAccount')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-walletAccount" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-walletAccount" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.walletAccount}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.walletAccount}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.walletAccount}" method="POST">
                <fieldset class="form">
                    <f:all bean="walletAccount"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

CoinBroker/grails-app/views/walletAccount/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'walletAccount.label', default: 'WalletAccount')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-walletAccount" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-walletAccount" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.walletAccount}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.walletAccount}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.walletAccount}" method="PUT">
                <g:hiddenField name="version" value="${this.walletAccount?.version}" />
                <fieldset class="form">
                    <f:all bean="walletAccount"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

CoinBroker/grails-app/views/walletAccount/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'walletAccount.label', default: 'WalletAccount')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-walletAccount" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-walletAccount" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${walletAccountList}" />

            <div class="pagination">
                <g:paginate total="${walletAccountCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

CoinBroker/grails-app/views/walletAccount/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'walletAccount.label', default: 'WalletAccount')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-walletAccount" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-walletAccount" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="walletAccount" />
            <g:form resource="${this.walletAccount}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.walletAccount}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>